package com.example.tppoo;
public enum Categorie {
    MEDICAL_HISTORY, MEDICAL_FOLLOWUP, // Categories for adults
    FAMILY_STRUCTURE, FAMILY_DYNAMICS, FAMILY_HISTORY, BIRTH_CONDITIONS, 
    PSYCHOMOTOR_DEVELOPMENT, LANGUAGE_DEVELOPMENT, CHARACTER_BEHAVIOR // Categories for children
}
